### ISSUE TITLE
Project update?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ECS-251-W2020/final-project-sudo#32]
is this promising project stalled or still alive?
I'm looking for a remote browser to run legacy Flash on my website
involving local mic/camera and streaming.
is Skia support it?
thanks

**Comment by kingdido999** [comment]
Hey @ROBERT-MCDOWELL, thanks for checking in. This project is no longer active, you might want to look for something else.

**Comment by ROBERT-MCDOWELL** [comment]
sad :(
